name: CI

on:
  push:
    branches: [ main, master, develop, '*' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.12'

      - name: Sync dependencies (dev)
        run: |
          uv sync --extra dev

      - name: Lint
        run: |
          make lint

      - name: Test
        env:
          PYTHONPATH: .
        run: |
          make test

